version: '3.9'

services:
  postgres:
    build: ./postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: satisfacao
    ports:
      - "5432:5432"
    networks:
      - app-network

  mongodb:
    build: ./mongodb
    container_name: mongodb_container
    ports:
      - "27017:27017"
    networks:
      - app-network

  nodeapp:
    build: ./node
    container_name: node_app_container
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
